- name: 'add vs code apt key'
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: 'present'
  register: 'add_repository_key'
  ignore_errors: true
- name: Add vs code APT repository
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    state: present
    update_cache: 'yes'
- name: Instal1 docker and prereqs
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - code