- name: install docker apt key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: install docker repository
  command: apt-add-repository repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable

- name: update apt
  apt: update

- name: install docker
  command: apt-cache policy docker-ce

- name: Add user to docker
  command: usermod -a -G docker drew