- name: install docker apt key
  apt_key:
    https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: install docker repository
  command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: update apt and install docker
  command: apt update && apt-cache policy docker-ce

- name: Add user to docker
  command: usermod -a -G docker drew