- name: Install arc theme
  apt: name=arc-theme

- name: Install psutil package
  apt: name=python-psutil

- name: Copy wallpaper file
  copy: src=files/boatwallpaper.jpg dest=/home/drew/.wallpaper.jpg owner=drew group=drew mode=600

- name: Set GNOME wallpaper
  become_user: drew
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/drew/.wallpaper.jpg'"

- name: Set GTK theme
  become_user: drew
  dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Arc'"
